### ISSUE TITLE
vue项目 英文翻译中的index.js文件无法生成对应的翻译对象

### ISSUE THREAD

**Issue by lifeLikeACode** [mr18/webpack-i18n-plugin#1]
vue项目 英文翻译中的index.js文件无法生成对应的翻译对象

**Comment by mr18** [comment]
参考[DEMO](./demo)配置翻译文件.xlsx
const i18nConfig = {
  translation: {
    en_US: [path.resolve(__dirname, "翻译文件.xlsx")], 
  },
};

**Comment by lifeLikeACode** [comment]
你看下你的\demo\vue2\output\en_US\index.js中的内容是空的 但是react项目中的内容是正常的

**Comment by mr18** [comment]
[翻译文件格式参考](https://github.com/mr18/webpack-i18n-plugin/blob/master/demo/react/output/en_US/%E7%BF%BB%E8%AF%91%E5%86%85%E5%AE%B9.xlsx)

**Comment by mr18** [comment]
> 
`vue2`由于`i18n.config.js`注释了翻译配置，所以没有语言包生成

```
translation: {
    en_US: [
      // path.resolve(__dirname, "./i18n/en_US/翻译内容.xlsx")
    ],
  },
```

**Comment by lifeLikeACode** [comment]
![image](https://user-images.githubusercontent.com/20747867/163094460-0ab94c27-686d-4d59-bdda-735ddea67cf0.png)

我打包vue项目无法生成对应的key value 不是说翻译的文件没有 你的demo中vue项目也是没有对应的英文的内容的 这个是正常的吗

**Comment by lifeLikeACode** [comment]
> resolve

好的谢谢 了解了

**Comment by mr18** [comment]
如果出现语言包无法更新，尝试清理node_modules/.cache（导致的不会重新编译）

**Comment by lifeLikeACode** [comment]
> 如果出现语言包无法更新，尝试清理node_modules/.cache目录（导致的不会重新编译）

好的 我尝试下
